DELETE http://localhost:8080/note/de7a4006-1ef1-4fe8-9900-4cfb6aa5de90
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwczovL25vdHktYXBpLmhlcm9rdWFwcC5jb20iLCJpc3MiOiJOb3R5S1QtSldULUlzc3VlciIsInVzZXJJZCI6Ijg4NTlhZDI0LWU4NTgtNGFmYi1hN2Y2LTBiZTcxYTMwN2JjOSJ9.sG6NREiAqYhx0HcF_GprQ-ltavDqto0O93X_E5ea2pQ
