name: Deploy (API)

on:
  push:
    branches:
      - master
      
    paths:
      - 'noty-api/**'

jobs:
  deploy_api:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      
      - name: Deploy to Heroku
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ secrets.HEROKU_USER_EMAIL }}
          echo "$HEROKU_AUTH" > ~/.netrc
          heroku git:remote --app noty-api
          git push heroku `git subtree split --prefix noty-api master`:master --force
        env:
          HEROKU_AUTH: ${{ secrets.HEROKU_AUTH }}
